### ISSUE TITLE
升级Xcode10 SDK报错Symbol not found: __T0BOWV

### ISSUE THREAD

**Issue by huluo666** [aliyun/aliyun-log-ios-sdk#12]
> dyld: Symbol not found: __T0BOWV
  Referenced from: /Users/apple10/Library/Developer/CoreSimulator/Devices/9E85D055-4FDB-4DEE-AE35-75396B3ACE4C/data/Containers/Bundle/Application/CF6C3F15-CA79-4AEB-8FBC-20BE4FBC2C8E/GameDemo.app/Frameworks/AliyunLOGiOS.framework/AliyunLOGiOS
  Expected in: /Users/apple10/Library/Developer/CoreSimulator/Devices/9E85D055-4FDB-4DEE-AE35-75396B3ACE4C/data/Containers/Bundle/Application/CF6C3F15-CA79-4AEB-8FBC-20BE4FBC2C8E/GameDemo.app/Frameworks/libswiftCore.dylib
 in /Users/apple10/Library/Developer/CoreSimulator/Devices/9E85D055-4FDB-4DEE-AE35-75396B3ACE4C/data/Containers/Bundle/Application/CF6C3F15-CA79-4AEB-8FBC-20BE4FBC2C8E/GameDemo.app/Frameworks/AliyunLOGiOS.framework/AliyunLOGiOS

**Comment by sunqingquan** [comment]
我也遇到同样的问题，希望阿里可以有一个解决办法，谢谢

**Comment by duan007a** [comment]
请更新到sdk的最新版本重新编译出framework然后使用
