### ISSUE TITLE
模拟器编译报错，形如：'LOGClient' is unavailable: cannot find Swift declaration for this class

### ISSUE THREAD

**Issue by wjling** [aliyun/aliyun-log-ios-sdk#14]
XCode 10，OC&Swift混编项目。导入脚本生成的两个framework，真机上编译通过，用模拟器编译报错。形如：
'LOGClient' is unavailable: cannot find Swift declaration for this class
'LogGroup' is unavailable: cannot find Swift declaration for this class
等。

**Comment by 1019272778** [comment]
打包脚本编译出来的framework库是Release版本,支持i386,x86_64,armv7,arm64的fat库。Fat方式暂不支持xcode10，详见：https://forums.developer.apple.com/thread/109583。如果用xcode10 开发请选择源码方式

**Comment by wjling** [comment]
我是把缺少的模拟器相关的东西手动拖到framework里面的...
