### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by sunzhongliangde** [aliyun/aliyun-log-ios-sdk#15]
XCode 10.0
OC代码集成报错dyld: Library not loaded: @rpath/libswiftCore.dylib
已按照要求确保General--Embedded Binaries中含有AliyunLOGiOS.framework以及依赖的FMDB.framework
确保Build Settings--Search Paths--Framework Search Paths中有AliyunLOGiOS.framework,FMDB.framework的文件路径
可以编译成功，运行起来就报错

**Comment by sunzhongliangde** [comment]
用的是build出来的 framework，工程中也开启了Embedded Content Contains Swift Code

**Comment by 1019272778** [comment]
打包脚本编译出来的framework库是fat库。Fat方式暂不支持xcode10，详见：https://forums.developer.apple.com/thread/109583。如果用xcode10 开发请选择源码方式
