### ISSUE TITLE
最新的SDK 在xcode10.2上面不能编译

### ISSUE THREAD

**Issue by ghost** [aliyun/aliyun-log-ios-sdk#17]
xocde升级最新的xcode10.2 不能编译通过,因为最新的SDK里有swift3的代码

**Comment by mengruirui** [comment]
我改了下源码，Swift 4 和 Swift 5都可以用，要的话可以加我QQ 1127631535，我私发你

**Comment by mengruirui** [comment]
https://github.com/mengruirui/aliyun-log-ios-sdk-master-swift5 这儿下载也行

**Comment by S-zin** [comment]
好的 谢谢您
________________________________
发件人: 孟瑞瑞 <notifications@github.com>
发送时间: 2019年4月11日 12:19
收件人: aliyun/aliyun-log-ios-sdk
抄送: Shawn; Author
主题: Re: [aliyun/aliyun-log-ios-sdk] 最新的SDK 在xcode10.2上面不能编译 (#17)


https://github.com/mengruirui/aliyun-log-ios-sdk-master-swift5 这儿下载也行

―

**Comment by jiangyancong** [comment]
> https://github.com/mengruirui/aliyun-log-ios-sdk-master-swift5 这儿下载也行

请问是用源码模式还是framework模式？用源码的时候，Tool.swift有颇多语法错误，我工程是swift4的。

**Comment by jiangyancong** [comment]
> https://github.com/mengruirui/aliyun-log-ios-sdk-master-swift5 这儿下载也行

我用frame build出来是没有 x86 ,但是用source build的话，tool.swift报错，请问是因为哪里设置还有问题么？

**Comment by mengruirui** [comment]
用frame 编译确实不支持模拟器，你可以直接用源码

**Comment by mengruirui** [comment]
> > https://github.com/mengruirui/aliyun-log-ios-sdk-master-swift5 这儿下载也行
> 
> 我用frame build出来是没有 x86 ,但是用source build的话，tool.swift报错，请问是因为哪里设置还有问题么？

用frame 编译确实不支持模拟器，你可以直接用源码

**Comment by jiangyancong** [comment]
> > > https://github.com/mengruirui/aliyun-log-ios-sdk-master-swift5 这儿下载也行
> > 
> > 
> > 我用frame build出来是没有 x86 ,但是用source build的话，tool.swift报错，请问是因为哪里设置还有问题么？
> 
> 用frame 编译确实不支持模拟器，你可以直接用源码

你好，我就是源码build不过，在tool.swift有挺多语法错误的。

**Comment by ckynj** [comment]
这么多问题也不更新下

**Comment by ckynj** [comment]
阿里日志SDK 这么多问题 也没人有更新

**Comment by mengruirui** [comment]
> > > > https://github.com/mengruirui/aliyun-log-ios-sdk-master-swift5 这儿下载也行
> > > 
> > > 
> > > 我用frame build出来是没有 x86 ,但是用source build的话，tool.swift报错，请问是因为哪里设置还有问题么？
> > 
> > 
> > 用frame 编译确实不支持模拟器，你可以直接用源码
> 
> 我一开始源码build不过，在tool.swift有挺多语法错误的。后来发现是bridge文件里面需要把
> 
> ```
>  #import <CommonCrypto/CommonCrypto.h>
> #import <zlib.h>
> ```
> 加到自己的bridge里面。

是的呢

**Comment by mengruirui** [comment]
> 阿里日志SDK 这么多问题 也没人有更新

是啊，自己弄吧
