### ISSUE TITLE
是不是没人维护呀，swift 5都出了，还没更新支持4

### ISSUE THREAD

**Issue by liusui** [aliyun/aliyun-log-ios-sdk#18]

**Comment by wjling** [comment]
同问。是不是已经放弃了这个项目了

**Comment by jiangyancong** [comment]
同问

**Comment by mengruirui** [comment]
> 同问

我改了下源码，Swift 4 和 Swift 5都可以用，要的话可以加我QQ 1127631535，我私发你

**Comment by mengruirui** [comment]
> 同问。是不是已经放弃了这个项目了

我改了下源码，Swift 4 和 Swift 5都可以用，要的话可以加我QQ 1127631535，我私发你

**Comment by mengruirui** [comment]
我改了下源码，Swift 4 和 Swift 5都可以用，要的话可以加我QQ 1127631535，我私发你

**Comment by mengruirui** [comment]
https://github.com/mengruirui/aliyun-log-ios-sdk-master-swift5  这儿下载也行

**Comment by liusui** [comment]
> https://github.com/mengruirui/aliyun-log-ios-sdk-master-swift5 这儿下载也行

多谢了

**Comment by ckynj** [comment]
是不是没人维护了，这项目是不是都放弃了
