### ISSUE TITLE
HTTPS 请求报错

### ISSUE THREAD

**Issue by haidibing** [aliyun/aliyun-log-ios-sdk#19]
error = Optional(Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “*****-hangzhou.sls.aliyuncs.com” which could put your confidential information at risk." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x6000029d2760>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9843, NSErrorPeerCertificateChainKey=(
    "<cert(0x7f92c3055a00) s: *.log.aliyuncs.com i: GlobalSign Organization Validation CA - SHA256 - G2>",
    "<cert(0x7f92c2854000) s: GlobalSign Organization Validation CA - SHA256 - G2 i: GlobalSign Root CA>"
), NSUnderlyingError=0x6000015b42a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x6000029d2760>, _kCFNetwork36
36
3D
CFStreamSSLErrorOriginalValue=-9843, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9843, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x7f92c3055a00) s: *.log.aliyuncs.com i: GlobalSign Organization Validation CA - SHA256 - G2>",
    "<cert(0x7f92c2854000) s: GlobalSign Organization Validation CA - SHA256 - G2 i: GlobalSign Root CA>"
)}}, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “***-hangzhou.sls.aliyuncs.com” which could put your confidential information at risk., NSErrorFailingURLKey=https://*******-hangzhou.sls.aliyuncs.com/logstores/***/shards/lb, NSErrorFailingURLStringKey=https://*******-hangzhou.sls.aliyuncs.com/logstores/****/shards/lb, NSErrorClientCertificateStateKey=0})

**Comment by chaolee50** [comment]
您好，可以加入我们的群吗，http://t.cn/AiRpol8C
详细看下这个问题

**Comment by willbetter** [comment]
这个问题有结论吗?  我的demo也有这个问题, endPoints设置成https就是这个错误, 设置http正常
