### ISSUE TITLE
LogClient初始化bug

### ISSUE THREAD

**Issue by BoySimonHu** [aliyun/aliyun-log-ios-sdk#20]
现象：LogClient使用便利方法生成对象和使用初始化方法生成对象，进行postLog时结果不同。通过便利方法生成的对象进行postLog时，请求回报错。

初步判断：LogClient的便利构造方法的token在初始化的时候会解包为空字符串而不是nil~
但在postLog方法中拼接header的时候，token的拼接是对token参数判空而不是判断字符串长度。最终导致了请求header中的字段不对。

**Comment by chaolee50** [comment]
可以试试最新版本

pod 'AliyunLogProducer', '~> 2.1.0'
