### ISSUE TITLE
pod install报错，下载不了

### ISSUE THREAD

**Issue by pizazzsy** [aliyun/aliyun-log-ios-sdk#25]
linkcircle@linkcircledeMBP LogDemo % pod install
Analyzing dependencies
Downloading dependencies
Installing AliyunLogProducer (2.1.0)

[!] Error installing AliyunLogProducer
[!] /usr/bin/git clone https://github.com/aliyun/aliyun-log-ios-sdk.git /var/folders/2q/kf6k0z916s3gkzqnwxgbwty00000gn/T/d20201027-2004-1khewp0 --template= --single-branch --depth 1 --branch 2.1.0

Cloning into '/var/folders/2q/kf6k0z916s3gkzqnwxgbwty00000gn/T/d20201027-2004-1khewp0'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by chaolee50** [comment]
这个是网络问题吧，git 没有拉下来

**Comment by pizazzsy** [comment]
网络正常。打开网页什么的都很快。git上下载其他东西都很快




| |
施勇
邮箱：sy_0425@163.com
|

签名由 网易邮箱大师 定制

在2020年10月28日 10:45，LI CHAO 写道：

这个是网络问题吧，git 没有拉下来

**Comment by chaolee50** [comment]
git clone 这个项目呢
参考这个试试
https://www.cnblogs.com/zjfjava/p/10392150.html

**Comment by pizazzsy** [comment]
git clone也下载不了。

**Comment by chaolee50** [comment]
> git clone也下载不了。

使用这个版本试下
```
pod 'AliyunLogProducer', '~> 2.2.0'
```
