### ISSUE TITLE
沙盒里找不到对应的sqlite文件。

### ISSUE THREAD

**Issue by duhongliang** [aliyun/aliyun-log-ios-sdk#26]
请问，2.2.4版本
LogProducerResult res = [client AddLog:log flush:0];
    NSLog(@"res %ld", res);
打印为res 0，
但是在沙盒里 找不到对应的sqlite文件。只有 .idx 和_000 结尾的两个文件。
请问哪里出错了吗？
还是不会生成sqlite文件？
是按照介绍里，初始化的SDK和config。

**Comment by chaolee50** [comment]
你好，不会生成sqlite文件，保存在.idx 和_000文件里

**Comment by duhongliang** [comment]
> 你好，不会生成sqlite文件，保存在.idx 和_000文件里

那请问，如何查看我存进去的明文数据呢？

**Comment by chaolee50** [comment]
> > 你好，不会生成sqlite文件，保存在.idx 和_000文件里
> 
> 那请问，如何查看我存进去的明文数据呢？

你好，这些数据缓存下来会自动重新发送的，发送成功之后会自动删除的，为什么要查看这些数据呢，需求是什么呢

**Comment by duhongliang** [comment]
> > > 你好，不会生成sqlite文件，保存在.idx 和_000文件里
> > 
> > 
> > 那请问，如何查看我存进去的明文数据呢？
> 
> 你好，这些数据缓存下来会自动重新发送的，发送成功之后会自动删除的，为什么要查看这些数据呢，需求是什么呢

需要自己查看一下出入的数据的正确性。

**Comment by chaolee50** [comment]
在日志服务上，查上传的数据呢
