### ISSUE TITLE
如何修改Topic的值呢？

### ISSUE THREAD

**Issue by luzsyn** [aliyun/aliyun-log-ios-sdk#27]
你好，请教个问题：项目中需要上传多个埋点(topic)，看代码里topic是通过LogProducerConfig实例对象设置的，那岂不是一个topic对应一个client对象了？那有100个topic就需要创建100个不同的client对象保存在一个Dictionary里，这个内存会不会太大了，有什么建议吗？

**Comment by chaolee50** [comment]
topic当成一个普通字段，在Log里设置是一样的
