### ISSUE TITLE
日志重复上传多条 且 内容不对

### ISSUE THREAD

**Issue by luzsyn** [aliyun/aliyun-log-ios-sdk#28]
版本：2.2.6
描述：开启断点续传功能后(SetPersistent:1)，发现一个相同的topic被重复上传了多条，且对应的内容不是该topic存放的内容

下面为Xcode打印的日志：
![image](https://user-images.githubusercontent.com/21351578/103845541-3e661400-50d7-11eb-8b80-d7103a2986be.png)
下面为阿里云日志平台显示的结果：
![image](https://user-images.githubusercontent.com/21351578/103845646-6d7c8580-50d7-11eb-9f34-d58fb530cf4e.png)

如果关闭断点续传功能，
![image](https://user-images.githubusercontent.com/21351578/103845676-7a00de00-50d7-11eb-9e2e-d1d3df4bad64.png)
![image](https://user-images.githubusercontent.com/21351578/103845685-7f5e2880-50d7-11eb-9dab-b740c11a45b9.png)

下面是代码截图：
上传日志方法只调用了一次
![image](https://user-images.githubusercontent.com/21351578/103845800-c2b89700-50d7-11eb-9cc8-6a582c5fb414.png)

**Comment by chaolee50** [comment]
client 应该是全局的，现在是每次打日志都新生成一个client吗？
topic是在构造client时设置的，如果想每条日志topic不同，可以当成普通字段设置到Log里

**Comment by luzsyn** [comment]
> client 应该是全局的，现在是每次打日志都新生成一个client吗？
> topic是在构造client时设置的，如果想每条日志topic不同，可以当成普通字段设置到Log里

是的，每次打日志都会生成client，是为了设置不同的topic才这样做的，我也尝试把topic放在log里（[log PutContent:@"__topic__" value:topic];）可是上传后，阿里云控制台就会多出一个__topic__0的字段；


![截屏2021-01-08 上午9 57 40-tuya](https://user-images.githubusercontent.com/21351578/103965358-85680e00-5198-11eb-9b18-5827716928bc.png)

**Comment by chaolee50** [comment]
topic换个名字呢，比如topic1 当层成普通字段来用呢

**Comment by luzsyn** [comment]
> topic换个名字呢，比如topic1 ，当成普通字段来用呢

当成普通字段就不能显示在顶部的位置了（阿里云控制台__topic__显示位置）。
我们项目里用的还是2018年用Swift语言写的那个版本，最近才发现整个框架都变了，想更新到最新版发现topic这个问题，还有其他解决方案吗？实在不行就只能手动设置topic字段了，多一个__topic__0就多一个吧......
