### ISSUE TITLE
swift 3 完全编不过

### ISSUE THREAD

**Issue by HyanCat** [aliyun/aliyun-log-ios-sdk#3]
完全编不过呀，为何这样的代码还打了 release 了。完全是半残品啊。

**Comment by lujiajing1126** [comment]
@HyanCat https://github.com/lujiajing1126/aliyun-log-ios-sdk/releases/tag/1.0.5
自己改了Swift3能跑的版本~

**Comment by HyanCat** [comment]
@lujiajing1126 现在用的就是你的版本。感谢~

**Comment by lujiajing1126** [comment]
@HyanCat 前两天连夜赶工了一个OC的版本，如果你那边是OC的应用的话，可以试试

https://github.com/lujiajing1126/AliyunLogObjc

**Comment by sandbeach** [comment]
@HyanCat 不好意思，Swift 3.0 变化比较大，还没有来得及改完，可以用2.3交叉编译
