### ISSUE TITLE
集成在RN 0.60以上，项目无法运行。出现错误：Unknown type name 'namespace'等。

### ISSUE THREAD

**Issue by lishanxin** [aliyun/aliyun-log-ios-sdk#32]
示例代码：https://github.com/lishanxin/ReactNativeDemo0_60_6.git
在Pod上集成，pod 'AliyunLogProducer', "2.2.27"，导致出现错误：
![image](https://user-images.githubusercontent.com/34839411/139029500-183ba5a5-4125-4467-9a88-1b3b220632cf.png)
![image](https://user-images.githubusercontent.com/34839411/139029558-3b52a3ac-5204-4d98-a515-3c6675e5413c.png)

**Comment by cnbleu** [comment]
你好，问题是否已经得到解决？

**Comment by cnbleu** [comment]
编译问题，先关闭。

**Comment by SliverYuki** [comment]
你好，同样的问题，请问如何解决的呢？

**Comment by SliverYuki** [comment]
> 你好，同样的问题，请问如何解决的呢？

找到原因了，Log 头文件与 RN 自带的 Yoga 中的 Log 重名导致路径解析错误了，暂时修改引用为 ./Log.h 解决
<img width="479" alt="image" src="https://github.com/aliyun/aliyun-log-ios-sdk/assets/19161689/5467712f-4720-4205-9bab-37574aa0b23b">

@cnbleu 麻烦修复一下，谢谢

**Comment by rocona** [comment]
@cnbleu Log 头文件与 RN 自带的 Yoga 中的 Log 重名导致路径解析错误解决一下呗
