### ISSUE TITLE
多个统计行为同时进行，后台出现窜表的问题

### ISSUE THREAD

**Issue by AperFF** [aliyun/aliyun-log-ios-sdk#33]
logstore要传不同的行为名称，按照demo中的方式进行配置上传，导致后台统计出现窜表，一个统计行为跑到另一个统计行为的表里。
猜测出现问题的原因：项目里有很多行为可能同时上报，导致初始化完client后,还没统计上，下一个行为的client就被创建了。

因为client里要用logstore字段，没法用单例的模式。

怎么解决？？？

**Comment by cnbleu** [comment]
> 

你好，是否创建了多个不同的 client？如果是，每个 client 的 **persistentFilePath** 需要设置为不一样的值。
