### ISSUE TITLE
AliyunLogProducer -[LogProducerClient AddLog:flush:] + 456   偶先 Crash

### ISSUE THREAD

**Issue by chinzsc** [aliyun/aliyun-log-ios-sdk#35]
![image](https://user-images.githubusercontent.com/7047336/141071063-83a7516e-d384-40a3-addd-809c748d62c4.png)

您好 我目前遇到的问题是 AddLog的时候崩溃，目前崩溃率还挺高，猜测的原因是目前业务覆盖多个国家，Client存在切换国家 再次new赋值情况，是否需要保持多个client 还是一个来回切换赋值，使用DestroyLogProducer 方法先释放掉。
还有就是 [_logClient DestroyLogProducer];  也会偶发Crash

**Comment by cnbleu** [comment]
你好，是否可以添加钉钉号详聊：cnbleu
