### ISSUE TITLE
iOS 9.1 Crash in Tag 2.3.7

### ISSUE THREAD

**Issue by qiming-guo** [aliyun/aliyun-log-ios-sdk#39]
<img width="495" alt="image" src="https://user-images.githubusercontent.com/13283159/156739083-06196c38-a3b6-44c9-9338-2548195fb8d5.png">
<img width="877" alt="image" src="https://user-images.githubusercontent.com/13283159/156739232-661dcb92-315a-4690-958d-364a7e253565.png">

**Comment by cnbleu** [comment]
可以使用2.3.9及以上的版本。
