### ISSUE TITLE
遇到一个线上crash

### ISSUE THREAD

**Issue by bingFly** [aliyun/aliyun-log-ios-sdk#42]
![image](https://user-images.githubusercontent.com/7598300/185338758-1f0ac5e9-27d7-4753-ad97-06b581a1ee01.png)

用的这里crashcrash了

**Comment by bingFly** [comment]
是内存不够了么？

**Comment by cnbleu** [comment]
> 是内存不够了么？

你好，使用的SDK版本是多少？

**Comment by cnbleu** [comment]
长时间没有回复，问题先关闭了
