### ISSUE TITLE
发送日志报401错误，签名错误

### ISSUE THREAD

**Issue by ahcfhy** [aliyun/aliyun-log-ios-sdk#45]
版本号：sls-ios-sdk_v2.2.8
问题描述：发送日志失败，返回结果401，提示签名错误
hmac-sha.c文件中的hmac_sha1 函数出现问题，任何输入数据，
签名出来的数据hmac-sha1均为：\345m\241}*F\306$\213M\200|\355Oe\246!R
base64后的结果为 5W2hFn0qRsYIJItNgHztEk9lpiE=
很令人费解，不知道是否是签名算法出现问题还是和别的函数、变量等有冲突。
敬请解答。

**Comment by cnbleu** [comment]
可能是底层库冲突了，SDK升级到3.1.7版本再尝试下。
